global:
  scrape_interval: 15s
  evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093


scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8084']

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'apigateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']


  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8087' ]

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8086' ]
