server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8081
    loadbalancer:
      enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transaction/**
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/account/**
  config:
    import: optional:configserver:http://localhost:8081
